# Generated by Django 5.1.4 on 2024-12-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberprofile",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="profile_images"),
        ),
    ]
